feat: added Tagged module
Effect-TS/data pull request #461
Opened 2023-08-17 22:14 UTC by jessekelly881

It might be useful to create a module for handling tagged objects. Esp. to help clean up the type definitions within io,stream.

2023-08-18 08:58 UTC, mikearnaldi commented
I see where you're coming from as objects with a tag are very frequent but I am a bit reluctant to add a module for the sake of two type helpers that are basically an alias of Extract / Exclude. Namely whenever we had to deal with tags it is to do different things, almost never a simple exclusion or similar so I guess to bring this forward we'd need a strong motivation with concrete examples of app code.

Alternatively: we do have a number of type helpers that really have no place and we've been discussing the creation of a Types module to put there commonly used types such as IsEqual / UnionToIntersection & co (cc @tim-smart / @gcanti)

2023-08-18 20:15 UTC, jessekelly881 commented
I'm inclined to agree with you. My first thought was actually to create a Types module and only went with a Tagged module because the types that I wanted to add were only specific to tagged objects.

2023-08-19 06:31 UTC, gcanti commented
in my TODO list there's an old "move UnionToIntersection to some centralized location", +1 for a Types module

2023-08-25 05:27 UTC, jessekelly881 commented
Converted to Types module.

2023-08-25 06:20 UTC, gcanti commented
@jessekelly881 There's also `type Simplify<A>` in `src/Data` (used for example in /schema).

However I would change it to:

```ts
export type Simplify<A> = {
  [K in keyof A]: A[K]
} extends infer B ? B : never
```

which IME produces shorter types in the emitted declaration files

2023-08-25 08:29 UTC, jessekelly881 commented
I didn't see that specific type-def (I'm probably missing just overlooking it). I added Simplify and moved Data/IsEqualTo -> Types.Equal

2023-08-25 16:18 UTC, gcanti commented
> I didn't see that specific type-def

you mean Simplify? is here https://github.com/Effect-TS/data/blob/62d6dc25f02dc489ce98399ae661fabdd00833e0/src/Data.ts#L191
(I guess you are a few commits behind `main`)

2023-08-25 21:20 UTC, jessekelly881 commented
I was indeed a few commits behind main. lol. Updated. :)

2023-08-26 04:06 UTC, jessekelly881 commented
I was indeed a few commits behind. Lol.

2023-08-28 16:02 UTC, gcanti requested changes

2023-08-28 16:02 UTC, gcanti commented on dtslint/Data.ts
> +// $ExpectType Data.Data<>
this is raising an error in the `dtslint` task (not sure what's the purpose of this file though)

2023-08-28 16:04 UTC, jessekelly881 commented on dtslint/Data.ts
> +// $ExpectType Data.Data<>
There isn't a point. Jaja This was something I was testing that slipped through. Let me clean this PR up(it's been neglected) and I will ping you in a bit when it's ready

2023-08-28 16:15 UTC, jessekelly881 commented on dtslint/Data.ts
> +// $ExpectType Data.Data<>
Fixed. :)

2023-08-28 16:16 UTC, jessekelly881 commented
Are there any other types that you guys can think of that we should add to this?

2023-08-28 16:52 UTC, gcanti approved these changes

2023-08-29 05:21 UTC, tim-smart commented
From /io:

<img width="778" alt="image" src="https://github.com/Effect-TS/data/assets/40680/e689bffa-695f-47eb-b3e1-7a04902d0295">

2023-08-30 15:56 UTC, mikearnaldi commented
LGTM @tim-smart if you want to push MergeRecord we can merge this

2023-08-31 00:16 UTC, jessekelly881 commented
I added it. I renamed it Type.Extend after S.extend and (at least to) me seems more clear. Any quarrels w/ that name instead?

2023-08-31 02:21 UTC, tim-smart commented
> I added it. I renamed it to Type.Extend after S.extend and (at least to me) that seems more clear. Any quarrels w/ that name instead?

I think if it is called Extend, the second type parameter should have priority when it comes to key conflicts.

2023-08-31 02:28 UTC, jessekelly881 commented
Make sense. Do you think it would be better to change the functionality or the name then?

2023-08-31 02:33 UTC, tim-smart commented
I think MergeRight and MergeLeft is good.

2023-08-31 02:52 UTC, tim-smart commented
@jessekelly881 if you can run `pnpm run docs` and then we can merge this :)

2023-08-31 03:05 UTC, merged