add encoding module
Effect-TS/data pull request #472
Opened 2023-08-24 06:43 UTC by fubhy

Re-opening this here.

2023-08-24 06:45 UTC, fubhy commented on src/internal/Encoding/Base64.ts
> +    throw new TypeError("Invalid base64 string")
@tim-smart If we return `Either` here, should I also remove the (then somewhat superfluous) `unsafeDecode` variants?

2023-08-24 20:50 UTC, tim-smart commented on src/internal/Encoding/Base64.ts
> +    throw new TypeError("Invalid base64 string")
Yes that keeps the module simple.

2023-08-24 20:56 UTC, tim-smart reviewed
Looking pretty good!

I'm not too worried about the performance - it is still really easy to use the Buffer api on node.js if you don't want to use this module.

2023-08-24 20:56 UTC, tim-smart commented on src/Encoding.ts
> + * @category encoding
Using a category of "decoding" for the decode apis would be a nice touch.

2023-08-24 20:56 UTC, tim-smart commented on src/internal/Encoding/Base64.ts
> +  readonly _tag = "Base64DecodeError"
I think adding a bit more context to the errors would be helpful. Maybe a copy of the offending input and a message?

2023-08-24 21:28 UTC, fubhy commented on src/internal/Encoding/Base64.ts
> +  readonly _tag = "Base64DecodeError"
@tim-smart Done! Let me know if you think the messages are descriptive enough.

2023-08-28 22:07 UTC, tim-smart requested changes

2023-08-28 22:07 UTC, tim-smart commented on src/internal/Encoding/Base64.ts
> +  readonly _tag = "Base64DecodeError"
Yes that is better :)

I think we should just have one error type for the entire module, and it should also be exported alongside a constructor. It should also have it's own TypeId in the same fashion as other error in the ecosystem (for example https://effect-ts.github.io/io/modules/Cause.ts.html#nosuchelementexception-interface). This prevents typescript from merging it, in the small chance someone decides to use the same _tag in another error.

Once errors are sorted I think we can merge this!

2023-08-29 10:22 UTC, fubhy commented on src/internal/Encoding/Base64.ts
> +  readonly _tag = "Base64DecodeError"
Done!

2023-08-29 10:24 UTC, fubhy commented
@tim-smart I kept the name `DecodeException`. Should we maybe call this "IncorrectEncodingException` or `InvalidEncodingException`?

2023-08-29 21:21 UTC, tim-smart requested changes

2023-08-29 21:21 UTC, tim-smart commented on src/internal/Encoding/Base64Url.ts
> +  return Base64.decode(sanitized).pipe(Either.mapLeft((e) => DecodeException(e.input, e.message)))
You don't need this mapLeft anymore.

2023-08-29 21:48 UTC, tim-smart approved these changes

2023-08-29 21:49 UTC, merged